import { z } from "zod";

import { moneySchema } from "@/lib/currency/money";

export const initialCatalogProductSchema = z.object({
  id: z.string().min(1),
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  name: z.string().min(1),
  summary: z.string().min(1),
  material: z.enum(["PLA", "ABS"]),
  weightGrams: z.number().int().positive(),
  dimensionsMm: z.object({ length: z.number().positive(), width: z.number().positive(), height: z.number().positive() }),
  colours: z.array(z.enum(["white", "black", "gray", "dark green", "tan", "latte brown", "red"])).min(1),
  finishes: z.array(z.enum(["Default", "Glossy"])).min(1),
  pricingFormula: z.string().min(1),
  limitations: z.array(z.string().min(1)).min(1),
  provisionalPrice: moneySchema,
  glossyBaseSurcharge: moneySchema,
  availability: z.discriminatedUnion("kind", [
    z.object({ kind: z.literal("in_stock"), quantity: z.number().int().positive(), label: z.union([z.literal("In stock"), z.string().regex(/^Only [1-5] Left$/)]) }),
    z.object({ kind: z.literal("made_to_order"), label: z.literal("Made to order") }),
    z.object({ kind: z.literal("unavailable"), label: z.literal("Sold out") }),
  ]),
  mediaStatus: z.literal("placeholder_pending_approved_media"),
});

export type InitialCatalogProduct = z.infer<typeof initialCatalogProductSchema>;

export const initialCatalogProducts = [
  {
    id: "monitor-riser",
    slug: "monitor-riser",
    name: "Monitor Riser",
    summary: "Product summary pending approval.",
    material: "PLA",
    weightGrams: 100,
    dimensionsMm: { length: 350, width: 250, height: 120 },
    colours: ["white", "black", "gray", "dark green", "tan", "latte brown", "red"],
    finishes: ["Default", "Glossy"],
    pricingFormula: "100 g × $0.05",
    limitations: ["Product limitations pending approval."],
    provisionalPrice: { amountMinor: 500, currency: "CAD" },
    glossyBaseSurcharge: { amountMinor: 200, currency: "CAD" },
    availability: { kind: "unavailable", label: "Sold out" },
    mediaStatus: "placeholder_pending_approved_media",
  },
  {
    id: "desk-tray",
    slug: "desk-tray",
    name: "Desk Tray",
    summary: "Product summary pending approval.",
    material: "PLA",
    weightGrams: 50,
    dimensionsMm: { length: 120, width: 180, height: 100 },
    colours: ["white", "black", "gray", "dark green", "tan", "latte brown", "red"],
    finishes: ["Default", "Glossy"],
    pricingFormula: "50 g × $0.05",
    limitations: ["Product limitations pending approval."],
    provisionalPrice: { amountMinor: 250, currency: "CAD" },
    glossyBaseSurcharge: { amountMinor: 100, currency: "CAD" },
    availability: { kind: "unavailable", label: "Sold out" },
    mediaStatus: "placeholder_pending_approved_media",
  },
  {
    id: "coat-hanger",
    slug: "coat-hanger",
    name: "Coat Hanger",
    summary: "Product summary pending approval.",
    material: "ABS",
    weightGrams: 15,
    dimensionsMm: { length: 400, width: 2, height: 150 },
    colours: ["white", "black", "gray", "dark green", "tan", "latte brown", "red"],
    finishes: ["Default", "Glossy"],
    pricingFormula: "15 g × $0.07",
    limitations: ["Product limitations pending approval."],
    provisionalPrice: { amountMinor: 105, currency: "CAD" },
    glossyBaseSurcharge: { amountMinor: 30, currency: "CAD" },
    availability: { kind: "unavailable", label: "Sold out" },
    mediaStatus: "placeholder_pending_approved_media",
  },
  {
    id: "keycap-fidget",
    slug: "keycap-fidget",
    name: "Keycap Fidget",
    summary: "Product summary pending approval.",
    material: "PLA",
    weightGrams: 10,
    dimensionsMm: { length: 100, width: 30, height: 30 },
    colours: ["white", "black", "gray", "dark green", "tan", "latte brown", "red"],
    finishes: ["Default", "Glossy"],
    pricingFormula: "10 g × $0.05 + $0.50",
    limitations: ["Product limitations pending approval."],
    provisionalPrice: { amountMinor: 100, currency: "CAD" },
    glossyBaseSurcharge: { amountMinor: 20, currency: "CAD" },
    availability: { kind: "unavailable", label: "Sold out" },
    mediaStatus: "placeholder_pending_approved_media",
  },
] as const satisfies readonly InitialCatalogProduct[];
